---
# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Details: Modules need to be implemented correctly or else you will lose network
# connectivity to all of your target hosts. It's extremely important that if your
# playbooks fail at this step, you STOP, troubleshoot and repair any issues!
- name: ensure that loop module is enabled
  lineinfile: dest=/etc/modules state=present line='loop'
  when: inventory_hostname in groups['target']
  tags:
    - target-mods

- name: ensure that lp module is enabled
  lineinfile: dest=/etc/modules state=present line='lp'
  when: inventory_hostname in groups['target']
  tags:
    - target-mods

- name: ensure that rtc module is enabled
  lineinfile: dest=/etc/modules state=present line='rtc'
  when: inventory_hostname in groups['target']
  tags:
    - target-mods

- name: ensure that bonding module is enabled
  lineinfile: dest=/etc/modules state=present line='bonding'
  when: inventory_hostname in groups['target']
  tags:
    - target-mods

- name: ensure that 8021q module is enabled
  lineinfile: dest=/etc/modules state=present line='8021q'
  when: inventory_hostname in groups['target']
  tags:
    - target-mods
