---
# Copyright 2016, JinkIT, and it's Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
- include: hosts-bootstrap.yml
- include: hosts-hostname.yml
- include: hosts-groups.yml
- include: hosts-users.yml
- include: hosts-tools.yml
- include: hosts-keys.yml
- include: hosts-timezone.yml
#- include: hosts-modules.yml
#- include: hosts-apt.yml
#- include: hosts-routes.yml
#- include: hosts-key-deploy.yml
#- include: hosts-networking.yml
